name: benchmarks
channels:
  - conda-forge
dependencies:
  - python=3.12.12
  - pip
  - numpy=2.2.6
  - pip:
    - qibo==0.2.23
    - qibojit==0.1.12
    - qiskit==1.4.5
    - qulacs==0.6.12
    - cirq==1.6.1
    - qsimcirq==0.22.0
    - qcgpu==0.1.1
    - projectq==0.8.0

